config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  devise_for :users
  resources :books do
    post :reserve, on: :member
  end
  resources :reservations, only: %i[index update show]
  resources :company_reservations, only: %i[index], path: "company-reservations"
  mount Sidekiq::Web => "/sidekiq" # mount Sidekiq::Web in your Rails app
  root "books#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/book.rb
class Book < ApplicationRecord
  enum genre: {
    software_engineering: 0,
    design: 1,
    project_management: 2,
    ruby: 3,
    rails: 4,
    elixir: 5,
    pheonix: 6,
    android: 7,
    ios: 8,
    finance: 9,
    productivity: 10,
    fantasy: 11
  }

  has_many :reservations, dependent: :destroy
  has_one :active_reservation, -> { active }, class_name: "Reservation"
  has_many :readers, through: :reservations, source: :user
  has_one :active_reader, through: :active_reservation, source: :user

  validates :title, :description, :cover_url, presence: true

  def available?
    active_reservation.blank?
  end

  def reserved?
    active_reservation.present?
  end
end

app/models/reservation.rb
class Reservation < ApplicationRecord
  belongs_to :user
  belongs_to :book

  validate :book_cannot_be_double_reserved, on: :create
  validate :user_cannot_reserve_multiple_books, on: :create
  validate :returned_on_cannot_be_in_the_past
  validate :returned_on_cannot_be_revised, on: :update

  delegate :reserved?, to: :book, prefix: true
  delegate :actively_reading?, to: :user, prefix: true

  scope :active, -> { where(returned_on: nil) }
  scope :inactive, -> { where.not(returned_on: nil) }

  def returned?
    returned_on.present?
  end

  private

  def book_cannot_be_double_reserved
    errors.add(:base, :book_already_reserved) if book_reserved?
  end

  def user_cannot_reserve_multiple_books
    errors.add(:base, :user_has_reservations) if user_actively_reading?
  end

  def returned_on_cannot_be_in_the_past
    if (returned_on.present? && returned_on < Date.today)
      errors.add(:returned_on, :past_date)
    end
  end

  def returned_on_cannot_be_revised
    errors.add(:returned_on, :cannot_be_revised) if returned_on_previously_changed?
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :reservations, dependent: :destroy
  has_one :active_reservation, -> { active }, class_name: 'Reservation'
  has_one :active_reading, through: :active_reservation, source: :book

  devise :database_authenticatable, :registerable, :rememberable, :validatable

  validates :first_name, :last_name, presence: true
  validates :email, uniqueness: true

  scope :admin_users, -> { where(is_admin: true) }

  def actively_reading?
    active_reading.present?
  end

  def full_name
    "#{first_name} #{last_name}"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :authenticate_user!
  before_action :set_book, only: %i[show edit update reserve destroy]

  def index
    @books = Book.all.order(created_at: :asc)
  end

  def show; end

  def edit; end

  def new
    @book = Book.new
  end

  def create
    result = CreateBook.new(book_params).perform

    if result.success?
      respond_to do |format|
        format.html do
          flash[:notice] = "#{result.book.title} was successfully added to the collection"
          redirect_to(books_path)
        end
        format.json { render json: { book: result.book }, status: :created }
      end
    else
      respond_to do |format|
        format.html do
          flash.now[:alert] = result.errors
          render :new, status: :unprocessable_entity
        end
        format.json { render json: { errors: result.errors }, status: :unprocessable_entity }
      end
    end
  end

  def update
    result = UpdateBook.new(@book, book_params).perform

    if result.success?
      respond_to do |format|
        format.html do
          flash[:notice] = "#{result.book.title} was successfully updated!"
          redirect_to(books_path)
        end
        format.json { render json: { book: result.book }, status: :created }
      end
    else
      respond_to do |format|
        format.html do
          flash.now[:alert] = result.errors
          render :edit, status: :unprocessable_entity
        end
        format.json { render json: { errors: result.errors }, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    result = DestroyBook.new(@book).perform

    if result.success?
      respond_to do |format|
        flash[:notice] = "#{result.book.title} was successfully removed from the collection"
        format.turbo_stream
        format.json { head :ok }
      end 
    else
      respond_to do |format|
        format.json { head :unprocessable_entity }
      end 
    end
  end

  def reserve
    result = ReserveBook.new(current_user, @book).perform

    if result.success?
      respond_to do |format|
        format.html do
          redirect_to(books_path, notice: "#{@book.title} was successfully reserved")
        end
        format.json { render json: { reservation: result.reservation }, status: :created }
      end
    else
      respond_to do |format|
        format.html do
          flash.now[:alert] = result&.errors
          render :show, status: :unprocessable_entity
        end
        format.json { render json: { errors: result&.errors }, status: :unprocessable_entity }
      end
    end
  end

  private

  def book_params
    params.require(:book).permit(:title, :description, :genre, :cover_url)
  end

  def set_book
    @book = Book.find(params[:id])
  end
end

app/controllers/company_reservations_controller.rb
class CompanyReservationsController < ApplicationController
    before_action :authenticate_user!
    before_action :set_active_company_reservations

    def index; end

    private

    def set_active_company_reservations
        @active_company_reservations = Reservation.includes(:user, :book)
                                                  .active
                                                  .where.not(user_id: current_user.id)
    end
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
    before_action :authenticate_user!
    before_action :set_reservations, only: %i[index]
    before_action :set_active_reservation, only: %i[update show]

    def index; end

    def show; end

    def update
        result = ReturnBook.new(@active_reservation).perform

        if result.success?
            respond_to do |format|
                format.html { redirect_to(reservations_path) }
                format.json { render json: { reservation: result.reservation }, status: :ok }
                format.turbo_stream
            end
        else
            respond_to do |format|
                format.json { render json: { errors: result&.errors }, status: :unprocessable_entity }
            end
        end
    end

    private 

    def set_reservations
        @reservations = current_user.reservations.includes(:book).order(created_at: :desc)
    end

    def set_active_reservation
        @active_reservation = Reservation.find_by!(user: current_user, returned_on: nil)
    rescue ActiveRecord::RecordNotFound
        head :not_found
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def format_genre(genre)
        genre.split("_").map(&:capitalize).join(" ")
    end
end

app/views/books/_form.html.erb
<%= form_with(model: @book) do |form| %>
    <div class="my-5 w-full">
        <%= form.label :title %>
        <%= form.text_field :title, class: "block shadow rounded-md w-full" %>
    </div>
    <div class="my-5 w-full">
        <%= form.label :genre %>
        <%= form.select :genre, Book.genres.keys, {}, { class: "block shadow rounded-md w-full" } %>
    </div>
    <div class="my-5 w-full">
        <%= form.label :description %>
        <%= form.text_area :description, rows: 10, class: "block shadow w-full" %>
    </div>
    <div class="my-5 w-full">
        <%= form.label :cover_url %>
        <%= form.text_field :cover_url, class: "block shadow rounded-md w-full" %>
    </div>
    <div class="py-8">
        <%= form.submit class: "w-full rounded-lg py-3 bg-green-600 text-white font-medium cursor-pointer" %>
    </div>
<% end %>

app/views/books/destroy.turbo_stream.erb
<%= turbo_stream.remove "#{dom_id(@book)}_row" %>

app/views/books/edit.html.erb
<div class="w-1/2 mx-auto">
    <h1 class="font-bold text-5xl pb-8">Edit</h1>
    <%= render "form" %>
</div>

app/views/books/index.html.erb
<div class="grid grid-cols-4 gap-10">
    <div class="col-span-1">
        <% if current_user.active_reservation %>
            <%= turbo_frame_tag("active_reservation_badge", src: reservation_path(current_user.active_reservation.id)) %>
        <% end %>
        <%= turbo_frame_tag("company_reservations", src: company_reservations_path) %>
    </div>
    <table class="col-span-3">
        <tbody>
            <% @books.each do |book| %>
                <tr id="<%= dom_id(book) %>_row" class='<%= cycle('bg-sky-50', 'bg-white') %>'>
                    <td class="w-40"><%= image_tag(book.cover_url, class: 'w-fill') %></td>
                    <td class="px-4">
                        <%= link_to(book_path(book)) do %>
                            <h1 class="text-xl font-bold mb-3 hover:underline"><%= book.title %></h1>
                        <% end %>
                        <p class="max-w-xl"><%= truncate(book.description, length: 200) %></p>
                    </td>
                    <td class="px-4">
                        <%= link_to("Edit", edit_book_path(book), class: "hover:underline") %>
                        <%= button_to("Delete", book_path(book), method: :delete, class: "mt-4 hover:underline") %>
                    </td>
                </tr>
            <% end %>
        </tbody>
        <tfoot>
            <tr>
                <td>
                    <div class="my-8">
                        <%= link_to("New Book", new_book_path, class: "inline rounded-lg p-3 bg-green-600 text-white block font-medium") %>
                    </div>
                </td>
            </tr>
        </tfoot>
    </table>
</div>

app/views/books/new.html.erb
<div class="w-1/2 mx-auto">
    <h1 class="font-bold text-5xl pb-8">Add a new book</h1>
    <%= render "form" %>
</div>

app/views/books/show.html.erb
<div class="w-2/3 mx-auto">
    <h1 class="font-bold text-5xl pb-8"><%= @book.title %></h1>
    <div class="flex">
        <%= image_tag(@book.cover_url, class: "max-h-96 justify-start mr-8") %>
        <div class="flex flex-col">
            <span class="mb-5 text-sm text-white bg-sky-500 p-2 w-fit rounded-2xl shadow"><%= format_genre(@book.genre) %></span>
            <p><%= @book.description %></p>
            <div class="pt-12">
                <% if @book.reserved? %>
                    <div class="flex gap-2 items-center">
                        <%= image_tag("bookmark.svg", class: "w-5") %>
                        <p>
                            <span class="font-bold"><%= @book.active_reader.full_name %></span> reserved <%= @book.title %> on <%= @book.active_reservation.created_at.to_date %>
                        </p>
                    </div>
                <% elsif !current_user.actively_reading? %>
                    <%= button_to "Reserve book", reserve_book_path(@book), method: :post, class: "w-full rounded-lg py-3 bg-green-600 text-white font-medium cursor-pointer" %>
                <% end %>
            <div>
        </div>
    </div>
</div>

app/views/company_reservations/index.html.erb
<%= turbo_frame_tag("company_reservations") do %>
    <div class="bg-sky-50 shadow rounded p-6 mb-4 h-fit">
        <h3 class="font-bold mb-5">Company reservations</h3>
        <% @active_company_reservations&.each do |company_reservation| %>
            <div class="bg-white shadow rounded p-4 flex flex-col gap-4 mb-4">
                <%= link_to(book_path(company_reservation.book), "data-turbo-frame": "_top") do %>
                    <h4 class="font-bold hover:underline"><%= company_reservation.book.title %></h4>
                <% end %>
                <div class="flex flex-row w-full gap-2 items-center">
                    <%= image_tag("arrow-down.svg", class: "w-4") %>
                    <p>Reserved by <%= company_reservation.user.full_name %> on <%= company_reservation.created_at.to_date %></p>
                </div>
            </div>
        <% end %>
    </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookshelf</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render "shared/navbar" %>

    <main class="container mx-auto mt-28 px-5 flex flex-col items-center">
      <%= render "shared/flash" %>

      <%= yield %>
    </main>
  </body>
</html>

app/views/reservations/_row.html.erb
<tr id="<%= dom_id(reservation) %>_row" class='grid grid-cols-3 gap-4 p-4 <%= cycle('bg-sky-50', 'bg-white') %> shadow'>
    <td class="">
        <%= link_to(book_path(reservation.book), "data-turbo-frame": "_top") do %>
            <h2 class="font-bold text-md hover:underline"><%= reservation.book.title %></h2>
        <% end %>
    </td>
    <td class="flex gap-2 items-center justify-end">
        <%= image_tag("arrow-down.svg", class: "w-4") %>
        <%= reservation.created_at.to_date %>
    </td>
    <td class="flex gap-2 items-center justify-end">
        <% if reservation.returned? %>
            <%= image_tag("arrow-up.svg", class: "w-4") %>
            <%= reservation.returned_on %>
        <% else %>
            <%= button_to("Return book", reservation_path(reservation), method: :put, class: "hover:underline") %>
        <% end %>
    </td>
</tr>

app/views/reservations/index.html.erb
<div class="mx-auto">
    <h1 class="font-bold text-5xl pb-8">My reservations</h1>
    <table>
        <tbody>
            <% @reservations.each do |reservation| %>
               <%= render partial: "row", locals: { reservation: reservation } %> 
            <% end %>
        </tbody>
    </table>
</div>

app/views/reservations/show.html.erb
<%= turbo_frame_tag("active_reservation_badge") do %>
    <div class="bg-sky-50 shadow rounded p-6 mb-8 h-fit">
        <h3 class="font-bold mb-5">You're reading</h3>
        <div class="bg-white shadow rounded p-4 flex flex-col gap-4">
            <%= link_to(book_path(@active_reservation.book), "data-turbo-frame": "_top") do %>
                <h4 class="font-bold hover:underline"><%= @active_reservation.book.title %></h4>
            <% end %>
            <div class="flex flex-row w-full gap-2 items-center">
                <%= image_tag("arrow-down.svg", class: "w-4") %>
                <p>Reserved on <%= @active_reservation.created_at.to_date %></p>
            </div>
            <div class="flex w-full justify-center items-center">
            <%= button_to(
                "Return book",
                reservation_path(@active_reservation),
                method: :patch,
                form_class: "w-full",
                class: "w-full inline rounded-lg p-3 bg-green-600 text-white block font-medium"
            ) %>
            </div>
        </div>
    </div>
<% end %>

app/views/reservations/update.turbo_stream.erb
<%= turbo_stream.replace "#{dom_id(@active_reservation)}_row", partial: "reservations/row", locals: { reservation: @active_reservation } %>
<%= turbo_stream.replace "active_reservation_badge" %>

app/views/shared/_flash.html.erb
<% if user_signed_in? %>
    <% flash.each do |type, content| %>
        <div data-controller="dismiss">
            <% if type == "notice" %>
                <div 
                    class="flex bg-green-50 w-fit p-3 mb-8 rounded-lg shadow fixed bottom-0 right-8 cursor-pointer"
                    data-dismiss-target="notice"
                    data-action="click->dismiss#triggerDismiss"
                >
                <%= image_tag("check-circle.svg", class: "mr-1 w-4") %>
                <p><%= content %></p>
                </div>
            <% elsif type == "alert" %>
                <div class="fixed bottom-0 right-8">
                <% content.each do |message| %>
                    <div 
                        class="flex bg-red-50 w-64 p-3 mb-8 rounded-lg shadow cursor-pointer"
                        data-dismiss-target="alert"
                        data-action="click->dismiss#triggerDismiss"
                    >
                    <%= image_tag("xmark-circle.svg", class: "mr-1 w-4") %>
                    <p><%= message %></p>
                    </div>
                <% end %>
                </div>
            <% end %>
        </div>
    <% end %>
<% end %>

app/views/shared/_navbar.html.erb
<% if user_signed_in? %>
    <nav class="fixed top-0 left-0 right-0 bg-white/90 backdrop-blur-sm shadow-sm">
        <div class="flex p-3 mx-5 items-center justify-between">
            <%= link_to(books_path, "data-turbo": false) do %>
                <h1 class="font-bold text-xl">Bookshelf</h1>
            <% end %>
            <div class="flex gap-4 items-center">
                <%= link_to(reservations_path) do %>
                    <%= image_tag("bookmark.svg", class: "w-6") %>
                <% end %>
                <div class="flex gap-1">
                    <%= image_tag("user.svg", class: "w-5") %>
                    <span><%= current_user.first_name %></span>
                </div>
                <%= button_to destroy_user_session_path, method: :delete, class: "flex self-baseline" do %>
                    <%= image_tag("logout.svg", class: "w-5") %>
                <% end %>
            <div>
        </div>
    </nav>
<% end %>